/**
 * ids.ts — Deterministic ID generation for all entities.
 *
 * ID formats (from product_guide §5.3):
 *   post_id:       FB_000001, FB_000002, ...
 *   comment_id:    C_000001,  C_000002, ...
 *   reply_id:      R_000001,  R_000002, ...
 *   source_id:     S_000001,  S_000002, ...
 *   annotation_id: A_000001,  A_000002, ...
 *
 * IDs are generated by reading existing IDs and picking the next
 * available sequence number. Collision checks prevent duplicates.
 *
 * This module MUST NOT depend on UI state (AGENTS.md rule).
 */

// ────────────────────────────────────────────────────────────────────────────
// ID prefixes and patterns
// ────────────────────────────────────────────────────────────────────────────

export const ID_PREFIXES = {
  post: "FB_",
  comment: "C_",
  reply: "R_",
  source: "S_",
} as const;

export type EntityType = keyof typeof ID_PREFIXES;

const ID_PATTERNS: Record<EntityType, RegExp> = {
  post: /^FB_(\d{6})$/,
  comment: /^C_(\d{6})$/,
  reply: /^R_(\d{6})$/,
  source: /^S_(\d{6})$/,
};

// ────────────────────────────────────────────────────────────────────────────
// Format helpers
// ────────────────────────────────────────────────────────────────────────────

/**
 * Pad a sequence number to 6 digits and prepend the entity prefix.
 *
 * @example formatId("post", 1)  → "FB_000001"
 * @example formatId("comment", 42) → "C_000042"
 */
export function formatId(entity: EntityType, seq: number): string {
  return `${ID_PREFIXES[entity]}${String(seq).padStart(6, "0")}`;
}

// ────────────────────────────────────────────────────────────────────────────
// Parsing
// ────────────────────────────────────────────────────────────────────────────

/**
 * Extract the numeric sequence from a well-formed ID string.
 * Returns `null` if the string doesn't match the expected pattern.
 *
 * @example parseIdSequence("post", "FB_000042") → 42
 * @example parseIdSequence("comment", "garbage") → null
 */
export function parseIdSequence(
  entity: EntityType,
  id: string
): number | null {
  const match = id.match(ID_PATTERNS[entity]);
  if (!match) return null;
  return parseInt(match[1], 10);
}

/**
 * Validate that a string is a well-formed ID for the given entity type.
 */
export function isValidId(entity: EntityType, id: string): boolean {
  return ID_PATTERNS[entity].test(id);
}

// ────────────────────────────────────────────────────────────────────────────
// Generation
// ────────────────────────────────────────────────────────────────────────────

/**
 * Find the highest sequence number among a list of existing IDs.
 * Returns 0 if the list is empty or contains no valid IDs.
 */
export function findMaxSequence(
  entity: EntityType,
  existingIds: string[]
): number {
  let max = 0;
  for (const id of existingIds) {
    const seq = parseIdSequence(entity, id);
    if (seq !== null && seq > max) {
      max = seq;
    }
  }
  return max;
}

/**
 * Generate the next available ID for the given entity type.
 *
 * @param entity     - The entity type ("post", "comment", etc.)
 * @param existingIds - All IDs of this type currently in the workbook.
 * @returns The next sequential ID string.
 * @throws If the generated ID somehow collides (should never happen with
 *         correct sequential logic, but we check defensively).
 */
export function generateNextId(
  entity: EntityType,
  existingIds: string[]
): string {
  const maxSeq = findMaxSequence(entity, existingIds);
  const nextSeq = maxSeq + 1;
  const nextId = formatId(entity, nextSeq);

  // Defensive collision check
  if (existingIds.includes(nextId)) {
    throw new Error(
      `ID collision detected: ${nextId} already exists. ` +
        `This indicates a data integrity issue in the workbook.`
    );
  }

  return nextId;
}

/**
 * Generate N sequential IDs starting from the next available.
 * Used when saving a post with multiple comments/replies at once.
 *
 * @param entity      - The entity type
 * @param existingIds - All IDs of this type currently in the workbook.
 * @param count       - How many new IDs to generate.
 * @returns Array of new ID strings in sequential order.
 */
export function generateBatchIds(
  entity: EntityType,
  existingIds: string[],
  count: number
): string[] {
  const maxSeq = findMaxSequence(entity, existingIds);
  const ids: string[] = [];

  for (let i = 1; i <= count; i++) {
    const newId = formatId(entity, maxSeq + i);

    // Defensive collision check
    if (existingIds.includes(newId)) {
      throw new Error(
        `ID collision detected: ${newId} already exists. ` +
          `This indicates a data integrity issue in the workbook.`
      );
    }

    ids.push(newId);
  }

  return ids;
}
